### ISSUE TITLE
http://pattrn.co/ website shows (beautyfied) 404

### ISSUE THREAD

**Issue by COLABORATI** [pattrn-project/pattrn#1]
The main website for this project currently gives a beautyfied 404 to the viewer
`Nothing found. 
Sorry, the post you are looking for is not available. Maybe you want to perform a search?`

**Comment by fsbrg** [comment]
Thank you for letting us know. The website is back up again now.

On 12 Jan 2016, at 08:07, COLABORATI <notifications@github.com<mailto:notifications@github.com>> wrote:

The main website for this project currently gives a beautyfied 404 to the viewer
Nothing found
Sorry, the post you are looking for is not available Maybe you want to perform a search?
