### ISSUE TITLE
Add tooling / build-step

### ISSUE THREAD

**Issue by fspoettel** [pattrn-project/pattrn#5]
Hey,
I saw the Forensic Architects talk at logan and I am interested in helping out. After skimming the codebase, I believe it could really benefit from using a build step / splitting it up into modules that get combined at build-time. This would accomplish a couple of things:
- Improve load-times by dramatically decreasing number of http requests needed to render the project
- Easier dependency management by using npm instead of CDN-hosted versions
- Ability to split the codebase into smaller, more testable modules (over time), improving separation of concerns and code readability
- Ability to explicitly set dependencies for parts of the library, making it easier for future contributors to grasp what is needed for each functionality
- Ability to write and run unit-tests for parts of the library

If there is interest, I could take a shot at setting up the boilerplate

**Comment by hotzeplotz** [comment]
@fspoettel this would be very useful, thank you for offering to get this started!

could you give us a sense of the tooling you would propose to use? i assume something along the lines of your blaupause project? most setups involving a Gulp task layout like the one there - which is pretty much what i use on other projects - should be good.

**Comment by fspoettel** [comment]
@hotzeplotz my blaupause project uses webpack under the hood for scripts and I've grown really fond of it. webpack is insanely powerful in itself for simply building stuff, so if there is no need for functionality like browser-sync and a lot of file I/O, I would omit gulp and just stick with webpack (one could still add gulp later one without having to change big parts of the webpack-config). The build-step could be initiated by a npm script. (`npm run build` or `npm run watch`) Over time, it could integrate Babel / ES2015 to be able to make use of new language features (es6 modules or fat arrow functions are worth it alone imo)

**Comment by hotzeplotz** [comment]
@fspoettel sounds good to me - happy to use webpack.
most of the JS dependencies are on NPM - i had created a test package.json a while ago (just committed as hotzeplotz/pattrn@4069f1d6c530f925c88b367b57ff13f58106b99a if it can be of any help to get started).

**Comment by fspoettel** [comment]
@hotzeplotz thanks for the heads-up, I'll use the meta-data specified in your package.json and send a PR when it is ready. Should I also add a chapter to the readme or do you want to do that? What is jsdom used for on package.json? I couldn't find a ref in the code.

**Comment by hotzeplotz** [comment]
@fspoettel jsdom shouldn't be needed - IIRC was something i was testing in some branch.
i have actually just started working on this codebase, which was developed before i joined the project, so i am not 100% familiar with the code as i'm just starting cleaning it up and extending it after focusing on backend/API work, but jsdom should definitely be safe to be left out.

i'll refactor/update the guide soon, but it would be useful if you could pop a brief overview of how to build assets in a separate documentation file (or in this thread) and i'll write everything up, thank you.

**Comment by hotzeplotz** [comment]
@fspoettel have you had a chance to get started on this?
i tweaked the current code in a private repo to add some short-term functionality that we needed for an ongoing project, but i will be starting a thorough refactor next week: i will try to at least switch to npm for dependencies while doing this.

**Comment by hotzeplotz** [comment]
this is now ready in a feature branch in my fork, with a plain Gulp configuration that builds JS assets via browserify and babel, and uses Pug/Jade for HTML templates. libsass to come next once we get full on with responsive design and themable interface.
